version: 1
formatters:
  simple:
    format: "[%(asctime)s] - %(name)s - %(levelname)s - %(message)s"
    datefmt: '%Y-%m-%d %H:%M:%S'
  simple-with-source-type:
    format: "[%(asctime)s] - [%(source_type)s] - %(name)s - %(levelname)s - %(message)s"
    datefmt: '%Y-%m-%d %H:%M:%S'
handlers:
  console:
    (): logger.ConsoleHandler
    level: DEBUG
    formatter: simple-with-source-type
    stream: ext://sys.stdout
  file:
    class: logger.FileHandler
    formatter: simple-with-source-type
    filename: logs/df.log
    when: midnight
    interval: 1
  gui:
    (): logger.GuiHandler
    level: DEBUG
    formatter: simple-with-source-type
loggers:
  core.worker.train_mri_gan_worker:
    level: DEBUG
    handlers: [file, gui, console]
    propagate: no
  core.worker.generate_mri_dataset_worker:
    level: DEBUG
    handlers: [file, gui, console]
    propagate: no 
  core.worker.landmark_extraction_worker:
    level: DEBUG
    handlers: [file, gui, console]
    propagate: no
  core.worker.crop_faces_worker:
    level: DEBUG
    handlers: [file, gui, console]
    propagate: no
  core.worker.frames_extraction_worker:
    level: DEBUG
    handlers: [file, gui, console]
    propagate: no
  core.worker.face_extraction_worker:
    level: DEBUG
    handlers: [file, gui, console]
    propagate: no
  core.dataset.dataset:
    level: DEBUG
    handlers: [file, gui, console]
    propagate: no
  core.trainer.trainer:
    level: DEBUG
    handlers: [file, gui, console]
    propagate: no
  core.scraper.google_images_scraper:
    level: DEBUG
    handlers: [file, gui, console]
    propagate: no
  trainer_thread:
    level: DEBUG
    handlers: [file, gui, console]
    propagate: no
  gui.pages.make_deepfake_page.tabs.data_tab:
    level: DEBUG
    handlers: [file, gui, console]
    propagate: no
  gui.pages.make_deepfake_page.training_tab:
    level: DEBUG
    handlers: [file, gui, console]
    propagate: no
  gui.pages.make_deepfake_page.detection_algorithm_tab:
    level: DEBUG
    handlers: [file, gui, console]
    propagate: no
  gui.pages.detect_deepfake_page.mri_gan.mri_gan_widget:
    level: DEBUG
    handlers: [file, gui, console]
    propagate: no
  gui.pages.detect_deepfake_page.mri_gan.train_mri_gan_widget:
    level: DEBUG
    handlers: [file, gui, console]
    propagate: no
  gui.pages.make_deepfake_page.inference_tab:
    level: DEBUG
    handlers: [file, gui, console]
    propagate: no
  gui.workers.io_worker:
    level: DEBUG
    handlers: [file, gui, console]
    propagate: no
  utils:
    level: DEBUG
    handlers: [console, gui, file]
    propagate: no
  core.extractor:
    level: DEBUG
    handlers: [console, file]
    propagate: no
  core.aligner:
    level: DEBUG
    handlers: [console, file]
    propagate: no
  gui.workers.inference_worker:
    level: DEBUG
    handlers: [console, gui, file]
    propagate: no
  gui.pages.detect_deepfake_page.mri_gan_widget:
    level: DEBUG
    handlers: [console, gui, file]
    propagate: no
  gui.widgets.configure_data_paths_dialog:
    level: DEBUG
    handlers: [console, gui, file]
    propagate: no
root:
  level: DEBUG
  handlers: [console, file]
