version: 1
formatters:
  simple:
    format: "[%(asctime)s] - %(name)s - %(levelname)s - %(message)s"
    datefmt: '%Y-%m-%d %H:%M:%S'
handlers:
  console:
    class: logging.StreamHandler
    level: DEBUG
    formatter: simple
    stream: ext://sys.stdout
  file:
    class: logging.handlers.TimedRotatingFileHandler
    formatter: simple
    filename: logs/df.log
    when: midnight
    interval: 1
  gui:
    (): logger.GuiHandler
    formatter: simple
    level: DEBUG
    formatter: simple
loggers:
  core.dataset.dataset:
    level: DEBUG
    handlers: [file, gui, console]
    propagate: no
  core.trainer.trainer:
    level: DEBUG
    handlers: [file, gui, console]
    propagate: no
  trainer_thread:
    level: DEBUG
    handlers: [file, gui, console]
    propagate: no
  gui.widgets.data_selector:
    level: DEBUG
    handlers: [file, gui, console]
    propagate: no
  gui.pages.make_deepfake_page.training_tab:
    level: DEBUG
    handlers: [file, gui, console]
    propagate: no
  gui.pages.make_deepfake_page.detection_algorithm_tab:
    level: DEBUG
    handlers: [file, gui, console]
    propagate: no
  gui.pages.make_deepfake_page.inference_tab:
    level: DEBUG
    handlers: [file, gui, console]
    propagate: no
  gui.workers.io_worker:
    level: DEBUG
    handlers: [file, gui, console]
    propagate: no
  utils:
    level: DEBUG
    handlers: [console, gui, file]
    propagate: no
  core.extractor:
    level: DEBUG
    handlers: [console, file]
    propagate: no
  core.aligner:
    level: DEBUG
    handlers: [console, file]
    propagate: no
  gui.workers.inference_worker:
    level: DEBUG
    handlers: [console, gui, file]
    propagate: no
root:
  level: DEBUG
  handlers: [console, file]
