# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'app_page.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_app(object):
    def setupUi(self, app):
        app.setObjectName("app")
        app.resize(935, 801)
        self.centralwidget = QtWidgets.QWidget(app)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.stacked_widget = QtWidgets.QStackedWidget(self.centralwidget)
        self.stacked_widget.setObjectName("stacked_widget")
        self.page = QtWidgets.QWidget()
        self.page.setObjectName("page")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.page)
        self.verticalLayout.setObjectName("verticalLayout")
        self.main_layout = QtWidgets.QVBoxLayout()
        self.main_layout.setObjectName("main_layout")
        self.label = QtWidgets.QLabel(self.page)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.main_layout.addWidget(self.label)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.main_layout.addItem(spacerItem)
        self.make_deepfake_btn = QtWidgets.QPushButton(self.page)
        self.make_deepfake_btn.setMinimumSize(QtCore.QSize(200, 0))
        self.make_deepfake_btn.setMaximumSize(QtCore.QSize(200, 16777215))
        self.make_deepfake_btn.setObjectName("make_deepfake_btn")
        self.main_layout.addWidget(self.make_deepfake_btn, 0, QtCore.Qt.AlignHCenter)
        self.detect_deepfake_btn = QtWidgets.QPushButton(self.page)
        self.detect_deepfake_btn.setMinimumSize(QtCore.QSize(200, 0))
        self.detect_deepfake_btn.setMaximumSize(QtCore.QSize(200, 16777215))
        self.detect_deepfake_btn.setObjectName("detect_deepfake_btn")
        self.main_layout.addWidget(self.detect_deepfake_btn, 0, QtCore.Qt.AlignHCenter)
        self.verticalLayout.addLayout(self.main_layout)
        self.stacked_widget.addWidget(self.page)
        self.page_2 = QtWidgets.QWidget()
        self.page_2.setObjectName("page_2")
        self.stacked_widget.addWidget(self.page_2)
        self.verticalLayout_2.addWidget(self.stacked_widget)
        app.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(app)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 935, 26))
        self.menubar.setObjectName("menubar")
        app.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(app)
        self.statusbar.setObjectName("statusbar")
        app.setStatusBar(self.statusbar)

        self.retranslateUi(app)
        self.stacked_widget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(app)

    def retranslateUi(self, app):
        _translate = QtCore.QCoreApplication.translate
        app.setWindowTitle(_translate("app", "MainWindow"))
        self.label.setText(_translate("app", "Deepfake"))
        self.make_deepfake_btn.setText(_translate("app", "Make deepfake"))
        self.detect_deepfake_btn.setText(_translate("app", "Detect deepfake"))
