# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main_page_2.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_main_page(object):
    def setupUi(self, main_page):
        main_page.setObjectName("main_page")
        main_page.resize(843, 710)
        main_page.setBaseSize(QtCore.QSize(200, 0))
        self.centralwidget = QtWidgets.QWidget(main_page)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.splitter = QtWidgets.QSplitter(self.centralwidget)
        self.splitter.setOrientation(QtCore.Qt.Vertical)
        self.splitter.setObjectName("splitter")
        self.stacked_widget = QtWidgets.QStackedWidget(self.splitter)
        self.stacked_widget.setObjectName("stacked_widget")
        self.page = QtWidgets.QWidget()
        self.page.setObjectName("page")
        self.stacked_widget.addWidget(self.page)
        self.page_2 = QtWidgets.QWidget()
        self.page_2.setObjectName("page_2")
        self.stacked_widget.addWidget(self.page_2)
        self.verticalLayoutWidget = QtWidgets.QWidget(self.splitter)
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(10, 0, 10, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.console = QtWidgets.QTextEdit(self.verticalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.console.sizePolicy().hasHeightForWidth())
        self.console.setSizePolicy(sizePolicy)
        self.console.setMinimumSize(QtCore.QSize(0, 30))
        self.console.setBaseSize(QtCore.QSize(0, 0))
        self.console.setObjectName("console")
        self.verticalLayout.addWidget(self.console)
        self.verticalLayout_2.addWidget(self.splitter)
        main_page.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(main_page)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 843, 26))
        self.menubar.setObjectName("menubar")
        main_page.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(main_page)
        self.statusbar.setObjectName("statusbar")
        main_page.setStatusBar(self.statusbar)

        self.retranslateUi(main_page)
        QtCore.QMetaObject.connectSlotsByName(main_page)

    def retranslateUi(self, main_page):
        _translate = QtCore.QCoreApplication.translate
        main_page.setWindowTitle(_translate("main_page", "MainWindow"))
