# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main_page.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_main_page(object):
    def setupUi(self, main_page):
        main_page.setObjectName("main_page")
        main_page.resize(922, 785)
        self.centralwidget = QtWidgets.QWidget(main_page)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.stacked_widget = QtWidgets.QStackedWidget(self.centralwidget)
        self.stacked_widget.setObjectName("stacked_widget")
        self.page = QtWidgets.QWidget()
        self.page.setObjectName("page")
        self.stacked_widget.addWidget(self.page)
        self.page_2 = QtWidgets.QWidget()
        self.page_2.setObjectName("page_2")
        self.stacked_widget.addWidget(self.page_2)
        self.verticalLayout_2.addWidget(self.stacked_widget)
        main_page.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(main_page)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 922, 26))
        self.menubar.setObjectName("menubar")
        main_page.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(main_page)
        self.statusbar.setObjectName("statusbar")
        main_page.setStatusBar(self.statusbar)

        self.retranslateUi(main_page)
        QtCore.QMetaObject.connectSlotsByName(main_page)

    def retranslateUi(self, main_page):
        _translate = QtCore.QCoreApplication.translate
        main_page.setWindowTitle(_translate("main_page", "MainWindow"))
