# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'start_page.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_start_page(object):
    def setupUi(self, start_page):
        start_page.setObjectName("start_page")
        start_page.resize(800, 600)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(start_page.sizePolicy().hasHeightForWidth())
        start_page.setSizePolicy(sizePolicy)
        start_page.setMinimumSize(QtCore.QSize(800, 600))
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(start_page)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setContentsMargins(-1, 20, -1, 50)
        self.verticalLayout.setSpacing(20)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(start_page)
        font = QtGui.QFont()
        font.setPointSize(18)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.make_deepfake_btn = QtWidgets.QPushButton(start_page)
        self.make_deepfake_btn.setMinimumSize(QtCore.QSize(250, 0))
        self.make_deepfake_btn.setMaximumSize(QtCore.QSize(250, 16777215))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.make_deepfake_btn.setFont(font)
        self.make_deepfake_btn.setObjectName("make_deepfake_btn")
        self.verticalLayout.addWidget(self.make_deepfake_btn, 0, QtCore.Qt.AlignHCenter)
        self.detect_deepfake_btn = QtWidgets.QPushButton(start_page)
        self.detect_deepfake_btn.setMinimumSize(QtCore.QSize(250, 0))
        self.detect_deepfake_btn.setMaximumSize(QtCore.QSize(250, 16777215))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.detect_deepfake_btn.setFont(font)
        self.detect_deepfake_btn.setObjectName("detect_deepfake_btn")
        self.verticalLayout.addWidget(self.detect_deepfake_btn, 0, QtCore.Qt.AlignHCenter)
        self.verticalLayout_2.addLayout(self.verticalLayout)

        self.retranslateUi(start_page)
        QtCore.QMetaObject.connectSlotsByName(start_page)

    def retranslateUi(self, start_page):
        _translate = QtCore.QCoreApplication.translate
        start_page.setWindowTitle(_translate("start_page", "Form"))
        self.label.setText(_translate("start_page", "Deepfake"))
        self.make_deepfake_btn.setText(_translate("start_page", "Make deepfake"))
        self.detect_deepfake_btn.setText(_translate("start_page", "Detect deepfake"))
